//! Playlist data model.
//!
//! A playlist is a named, ordered list of library track IDs plus a `kind` tag
//! distinguishing user-curated lists (`Manual`) from output of the
//! recommender (`Generated`). Both share one struct so every downstream
//! operation (rename, delete, sync, browse, reorder) is the same code path.
//!
//! Persistence lives in [`crate::playlist_store`]; the recommender that
//! consumes `GenerationParams` will land in Phase 2.

use serde::{Deserialize, Serialize};
use std::time::SystemTime;

/// Hash a `(created_at_ms, name)` pair into a stable playlist ID. Plain
/// FNV-1a so we don't pull in another hashing crate just for this — the
/// space is tiny (handfuls of playlists) and collisions only matter against
/// other playlists in the same file, which the store double-checks at insert
/// time.
pub(crate) fn hash_playlist_id(created_at_ms: u64, name: &str) -> u64 {
    const FNV_OFFSET: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut h = FNV_OFFSET;
    for b in created_at_ms.to_le_bytes().iter().chain(name.as_bytes()) {
        h ^= *b as u64;
        h = h.wrapping_mul(FNV_PRIME);
    }
    h
}

/// Current unix time in milliseconds, or `0` if the system clock is before
/// the epoch. Mirrors `local_plays::now_unix_ms` so callers don't have to
/// import both modules.
pub fn now_unix_ms() -> u64 {
    SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct Playlist {
    pub id: u64,
    pub name: String,
    pub kind: PlaylistKind,
    pub track_ids: Vec<u64>,
    pub created_at_ms: u64,
    pub updated_at_ms: u64,
    /// IDs of tracks generated by previous runs of this playlist's
    /// `Generate*` command. Used as a soft penalty during regeneration so
    /// "regenerate the same playlist" drifts instead of repeats. Manual
    /// playlists leave this empty.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub previously_recommended: Vec<u64>,
}

impl Playlist {
    /// Build a fresh manual playlist with a stable ID derived from
    /// `(now_ms, name)`. Caller is responsible for ensuring `name` is unique
    /// within the store; the store enforces that on insert.
    pub fn new_manual(name: impl Into<String>) -> Self {
        let name = name.into();
        let now = now_unix_ms();
        Playlist {
            id: hash_playlist_id(now, &name),
            name,
            kind: PlaylistKind::Manual,
            track_ids: Vec::new(),
            created_at_ms: now,
            updated_at_ms: now,
            previously_recommended: Vec::new(),
        }
    }

    /// Build a fresh generated playlist seeded with the recommender output
    /// and the params that produced it. `track_ids` is the recommender's
    /// final ordered selection; `previously_recommended` starts empty since
    /// this is the first run.
    pub fn new_generated(
        name: impl Into<String>,
        params: GenerationParams,
        track_ids: Vec<u64>,
    ) -> Self {
        let name = name.into();
        let now = now_unix_ms();
        Playlist {
            id: hash_playlist_id(now, &name),
            name,
            kind: PlaylistKind::Generated {
                params,
                last_generated_ms: now,
            },
            track_ids,
            created_at_ms: now,
            updated_at_ms: now,
            previously_recommended: Vec::new(),
        }
    }

    pub fn is_generated(&self) -> bool {
        matches!(self.kind, PlaylistKind::Generated { .. })
    }

    pub fn len(&self) -> usize {
        self.track_ids.len()
    }

    pub fn is_empty(&self) -> bool {
        self.track_ids.is_empty()
    }

    /// Append a track ID if not already present. Returns `true` if added,
    /// `false` if the ID was already in the list (no-op duplicate guard).
    pub fn add_track(&mut self, track_id: u64) -> bool {
        if self.track_ids.contains(&track_id) {
            return false;
        }
        self.track_ids.push(track_id);
        self.updated_at_ms = now_unix_ms();
        true
    }

    /// Remove a track ID. Returns `true` if found and removed.
    pub fn remove_track(&mut self, track_id: u64) -> bool {
        match self.track_ids.iter().position(|id| *id == track_id) {
            Some(pos) => {
                self.track_ids.remove(pos);
                self.updated_at_ms = now_unix_ms();
                true
            }
            None => false,
        }
    }

    /// Move a track from `from` to `to`. Out-of-bounds indices are no-ops.
    pub fn move_track(&mut self, from: usize, to: usize) -> bool {
        if from >= self.track_ids.len() || to >= self.track_ids.len() || from == to {
            return false;
        }
        let id = self.track_ids.remove(from);
        self.track_ids.insert(to, id);
        self.updated_at_ms = now_unix_ms();
        true
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum PlaylistKind {
    Manual,
    Generated {
        params: GenerationParams,
        last_generated_ms: u64,
    },
}

/// Parameters that drive the recommender. Persisted alongside the playlist
/// so a regeneration uses the same knobs as the original generation.
///
/// Phase 2 wires up the recommender that consumes this; Phase 1 only needs
/// the type to exist so the on-disk schema is stable across phase boundaries.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct GenerationParams {
    pub seed_strategy: SeedStrategy,
    pub target_length: usize,
    pub max_per_artist: usize,
    pub max_per_album: usize,
    /// MMR diversity weight. Stored as a `u32` of the f32 bit pattern so
    /// `PartialEq`/`Eq` derive cleanly without `total_cmp` gymnastics —
    /// settings comparison only needs bitwise identity, not numeric
    /// closeness. Round-tripped through `f32::from_bits` at use sites.
    pub diversity_lambda_bits: u32,
    /// Novelty knob, same encoding as `diversity_lambda_bits`.
    pub novelty_bits: u32,
    pub weights: ScoringWeights,
    pub exclude_artists: Vec<String>,
    pub exclude_track_ids: Vec<u64>,
    pub exclude_on_device: bool,
}

impl GenerationParams {
    /// Sensible "Discover Weekly"-style defaults. The Phase 2 form modal
    /// pre-fills with these unless a user has saved overrides in
    /// `config.toml`.
    pub fn default_discover_weekly() -> Self {
        GenerationParams {
            seed_strategy: SeedStrategy::TopPlayed {
                window_days: 30,
                count: 10,
            },
            target_length: 25,
            max_per_artist: 2,
            max_per_album: 1,
            diversity_lambda_bits: 0.7f32.to_bits(),
            novelty_bits: 0.5f32.to_bits(),
            weights: ScoringWeights::default(),
            exclude_artists: Vec::new(),
            exclude_track_ids: Vec::new(),
            exclude_on_device: true,
        }
    }

    pub fn diversity_lambda(&self) -> f32 {
        f32::from_bits(self.diversity_lambda_bits)
    }

    pub fn novelty(&self) -> f32 {
        f32::from_bits(self.novelty_bits)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum SeedStrategy {
    /// Top-K by aggregate `play_count` over the trailing `window_days`.
    /// `window_days = 0` means "all time."
    TopPlayed { window_days: u32, count: usize },
    /// Most-recent K tracks by `last_played_at_ms`.
    RecentlyPlayed { count: usize },
    /// Single explicit seed track — drives the "more like this" action.
    Track(u64),
    /// Scoped exploration of one artist's catalog.
    Artist(String),
    /// Scoped exploration of one genre.
    Genre(String),
}

impl SeedStrategy {
    /// Short human-readable label for the playlist sidebar subtitle.
    pub fn short_name(&self) -> String {
        match self {
            SeedStrategy::TopPlayed { window_days, count } => {
                if *window_days == 0 {
                    format!("top-{count} all-time")
                } else {
                    format!("top-{count} last {window_days}d")
                }
            }
            SeedStrategy::RecentlyPlayed { count } => format!("recent-{count}"),
            SeedStrategy::Track(_) => "more like this".to_string(),
            SeedStrategy::Artist(name) => format!("artist: {name}"),
            SeedStrategy::Genre(name) => format!("genre: {name}"),
        }
    }
}

/// Per-feature weights for the scoring function. Stored as bit patterns
/// (see `GenerationParams`) so the parent type can derive `Eq` cleanly.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct ScoringWeights {
    pub w_genre_bits: u32,
    pub w_year_bits: u32,
    pub w_artist_bits: u32,
    pub w_recency_bits: u32,
    pub w_rating_bits: u32,
    pub w_skip_bits: u32,
    /// Phase 4 sequence-aware term: weight on the Markov bigram probability
    /// `P(candidate | seed)` derived from the listen log. Defaults to a
    /// modest 0.25 — high enough to bias toward "tracks the user actually
    /// plays after these seeds" once enough log data exists, low enough not
    /// to flatten the rest of the scorer for new users. `serde(default)` so
    /// playlists serialised before this field existed deserialise cleanly.
    #[serde(default = "default_w_sequence_bits")]
    pub w_sequence_bits: u32,
}

fn default_w_sequence_bits() -> u32 {
    0.25f32.to_bits()
}

impl Default for ScoringWeights {
    fn default() -> Self {
        ScoringWeights {
            w_genre_bits: 0.30f32.to_bits(),
            w_year_bits: 0.10f32.to_bits(),
            w_artist_bits: 0.30f32.to_bits(),
            w_recency_bits: 0.20f32.to_bits(),
            w_rating_bits: 0.05f32.to_bits(),
            w_skip_bits: 0.20f32.to_bits(),
            w_sequence_bits: default_w_sequence_bits(),
        }
    }
}

impl ScoringWeights {
    pub fn w_genre(&self) -> f32 {
        f32::from_bits(self.w_genre_bits)
    }
    pub fn w_year(&self) -> f32 {
        f32::from_bits(self.w_year_bits)
    }
    pub fn w_artist(&self) -> f32 {
        f32::from_bits(self.w_artist_bits)
    }
    pub fn w_recency(&self) -> f32 {
        f32::from_bits(self.w_recency_bits)
    }
    pub fn w_rating(&self) -> f32 {
        f32::from_bits(self.w_rating_bits)
    }
    pub fn w_skip(&self) -> f32 {
        f32::from_bits(self.w_skip_bits)
    }
    pub fn w_sequence(&self) -> f32 {
        f32::from_bits(self.w_sequence_bits)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_manual_starts_empty() {
        let p = Playlist::new_manual("My Faves");
        assert_eq!(p.name, "My Faves");
        assert!(p.is_empty());
        assert_eq!(p.kind, PlaylistKind::Manual);
        assert!(!p.is_generated());
        assert!(p.previously_recommended.is_empty());
    }

    #[test]
    fn add_track_dedupes() {
        let mut p = Playlist::new_manual("Faves");
        assert!(p.add_track(42));
        assert!(p.add_track(7));
        assert!(!p.add_track(42), "duplicate add should return false");
        assert_eq!(p.track_ids, vec![42, 7]);
    }

    #[test]
    fn add_track_bumps_updated_timestamp() {
        let mut p = Playlist::new_manual("Faves");
        let original = p.updated_at_ms;
        // Sleep is overkill — just assert the field is bumped to *some* value
        // (now_unix_ms() is monotonic at ms precision in practice, but we
        // can't assert > without a sleep, so just assert it's set).
        p.add_track(1);
        assert!(p.updated_at_ms >= original);
    }

    #[test]
    fn remove_track_returns_false_when_absent() {
        let mut p = Playlist::new_manual("Faves");
        p.add_track(1);
        assert!(!p.remove_track(99));
        assert!(p.remove_track(1));
        assert!(p.is_empty());
    }

    #[test]
    fn move_track_within_bounds() {
        let mut p = Playlist::new_manual("Faves");
        p.add_track(1);
        p.add_track(2);
        p.add_track(3);
        assert!(p.move_track(0, 2));
        assert_eq!(p.track_ids, vec![2, 3, 1]);
    }

    #[test]
    fn move_track_out_of_bounds_is_noop() {
        let mut p = Playlist::new_manual("Faves");
        p.add_track(1);
        p.add_track(2);
        assert!(!p.move_track(0, 5));
        assert!(!p.move_track(5, 0));
        assert!(!p.move_track(0, 0));
        assert_eq!(p.track_ids, vec![1, 2]);
    }

    #[test]
    fn id_is_stable_for_same_name_and_time() {
        // Two playlists built with `new_manual` at the (likely) same ms will
        // collide on ID — that's why the store re-derives unique IDs on
        // collision rather than trusting `new_manual` blindly. This test just
        // pins the helper's determinism.
        assert_eq!(
            hash_playlist_id(1000, "Faves"),
            hash_playlist_id(1000, "Faves")
        );
        assert_ne!(
            hash_playlist_id(1001, "Faves"),
            hash_playlist_id(1000, "Faves")
        );
        assert_ne!(
            hash_playlist_id(1000, "Other"),
            hash_playlist_id(1000, "Faves")
        );
    }

    #[test]
    fn generated_playlist_round_trips_seed_strategy() {
        let params = GenerationParams::default_discover_weekly();
        let p = Playlist::new_generated("DW", params.clone(), vec![10, 20, 30]);
        assert_eq!(p.track_ids, vec![10, 20, 30]);
        assert!(p.is_generated());
        match &p.kind {
            PlaylistKind::Generated { params: stored, .. } => {
                assert_eq!(stored, &params);
            }
            _ => panic!("expected Generated kind"),
        }
    }

    #[test]
    fn default_discover_weekly_has_sane_caps() {
        let p = GenerationParams::default_discover_weekly();
        assert_eq!(p.target_length, 25);
        assert_eq!(p.max_per_artist, 2);
        assert_eq!(p.max_per_album, 1);
        assert!(p.exclude_on_device);
        // The float-bit encoding round-trips losslessly.
        assert!((p.diversity_lambda() - 0.7).abs() < 1e-6);
        assert!((p.novelty() - 0.5).abs() < 1e-6);
    }

    #[test]
    fn scoring_weights_default_sums_consistent() {
        let w = ScoringWeights::default();
        assert!((w.w_genre() - 0.30).abs() < 1e-6);
        assert!((w.w_year() - 0.10).abs() < 1e-6);
        assert!((w.w_artist() - 0.30).abs() < 1e-6);
        assert!((w.w_recency() - 0.20).abs() < 1e-6);
        assert!((w.w_rating() - 0.05).abs() < 1e-6);
        assert!((w.w_skip() - 0.20).abs() < 1e-6);
    }

    #[test]
    fn seed_strategy_short_name_examples() {
        assert_eq!(
            SeedStrategy::TopPlayed {
                window_days: 30,
                count: 10
            }
            .short_name(),
            "top-10 last 30d"
        );
        assert_eq!(
            SeedStrategy::TopPlayed {
                window_days: 0,
                count: 5
            }
            .short_name(),
            "top-5 all-time"
        );
        assert_eq!(
            SeedStrategy::RecentlyPlayed { count: 20 }.short_name(),
            "recent-20"
        );
        assert_eq!(SeedStrategy::Track(42).short_name(), "more like this");
        assert_eq!(
            SeedStrategy::Artist("Boards of Canada".into()).short_name(),
            "artist: Boards of Canada"
        );
        assert_eq!(
            SeedStrategy::Genre("Ambient".into()).short_name(),
            "genre: Ambient"
        );
    }
}
